### PR TITLE
observations: require phone number

### PR DESCRIPTION
**Pull request by stevekuznetsov**
observations: make it clear that email is not shown to the public

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Observations: require a phone number on input

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
We need a decision from @charlotteguard about whether e-mail should be optional or required to move forward here.

**Comment by charlotteguard** [comment]
Email should be required.

**Comment by charlotteguard** [comment]
But phone number should not be required!

**Comment by stevekuznetsov** [comment]
Reading comprehension 0/10. Would you like us to clarify that phone number is optional in the parenthetical? `"(optional, never shared with the public)"`

**Pull request merged**
